language: node_js
sudo: false
cache:
  directories:
    - ~/.npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  - '9'
script:
  - npm run test
  - npm run build
after_success:
  - npm run test:coverage:generate
  - npm run test:coverage:report
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
